# Generated by Django 6.0.8 on 2026-09-03 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devirambar', '0003_abonelik_devir_akisi'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='abonelikkaydi',
            new_name='devirambar__aktif_1615eb_idx',
            old_name='devir_abone_aktif_ilce_idx',
        ),
        migrations.RenameIndex(
            model_name='devirbasvurusu',
            new_name='devirambar__durum_83e418_idx',
            old_name='devirambar_durum_olust_idx',
        ),
        migrations.RenameIndex(
            model_name='devirbasvurusu',
            new_name='devirambar__ilce_2f42a2_idx',
            old_name='devirambar_ilce_durum_idx',
        ),
        migrations.RenameIndex(
            model_name='devirbasvurusu',
            new_name='devirambar__sayac_s_d11f49_idx',
            old_name='devirambar_sayac_idx',
        ),
        migrations.RenameIndex(
            model_name='devirhareketi',
            new_name='devirambar__basvuru_a43575_idx',
            old_name='devirambar_hareket_idx',
        ),
    ]
