# Generated by Django 6.0.8 on 2026-08-19 08:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=100, unique=True)),
                ('kod', models.SlugField(max_length=100, unique=True)),
                ('panel_tipi', models.CharField(choices=[('admin', 'Sistem Yönetimi'), ('185', '185 Çağrı Merkezi'), ('sef', 'Şef / Koordinatör'), ('saha', 'Saha')], default='saha', max_length=20)),
                ('aktif', models.BooleanField(default=True)),
                ('aciklama', models.CharField(blank=True, max_length=250)),
            ],
            options={
                'ordering': ['ad'],
            },
        ),
        migrations.CreateModel(
            name='RolAtamaKurali',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aktif', models.BooleanField(default=True)),
                ('aciklama', models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='PersonelProfili',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefon', models.CharField(blank=True, max_length=20)),
                ('sicil_no', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('aktif', models.BooleanField(default=True)),
                ('musait', models.BooleanField(default=True)),
                ('son_aktivite', models.DateTimeField(blank=True, null=True)),
                ('kullanici', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='personel_profili', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
