# Generated by Django 6.0.8 on 2026-08-19 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('adres', '0001_initial'),
        ('talepler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personelprofili',
            name='uzmanlik_is_turleri',
            field=models.ManyToManyField(blank=True, related_name='uzman_personeller', to='talepler.isturu'),
        ),
        migrations.AddField(
            model_name='personelprofili',
            name='yetkili_ilceler',
            field=models.ManyToManyField(blank=True, related_name='yetkili_personeller', to='adres.ilce'),
        ),
        migrations.AddField(
            model_name='rol',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_roller', to='accounts.rol'),
        ),
        migrations.AddField(
            model_name='personelprofili',
            name='rol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='personeller', to='accounts.rol'),
        ),
        migrations.AddField(
            model_name='rolatamakurali',
            name='hedef_rol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hedef_kurallari', to='accounts.rol'),
        ),
        migrations.AddField(
            model_name='rolatamakurali',
            name='kaynak_rol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kaynak_kurallari', to='accounts.rol'),
        ),
        migrations.AddConstraint(
            model_name='rolatamakurali',
            constraint=models.UniqueConstraint(fields=('kaynak_rol', 'hedef_rol'), name='uq_rol_atama_kurali'),
        ),
    ]
