# Generated by Django 6.0.8 on 2026-08-27 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rol',
            name='calisma_kanali',
            field=models.CharField(choices=[('web', 'Web / PC'), ('mobil', 'Mobil Saha'), ('her_ikisi', 'Web + Mobil')], default='web', help_text='Bu role bağlı kullanıcıların operasyon ekranına hangi kanaldan gireceğini belirler.', max_length=20),
        ),
    ]
