# Generated by Django 6.0.8 on 2026-09-03 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_v29_calisma_kanali'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rol',
            name='panel_tipi',
            field=models.CharField(choices=[('admin', 'Sistem Yönetimi'), ('185', '185 Çağrı Merkezi'), ('sef', 'Şef / Koordinatör'), ('saha', 'Saha'), ('abone', 'Abone İşlemleri'), ('merkez_ambar', 'Merkez Ambar')], default='saha', max_length=20),
        ),
    ]
