# Generated by Django 6.0.8 on 2026-08-19 08:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('adres', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IsTuru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=120, unique=True)),
                ('kod', models.SlugField(max_length=120, unique=True)),
                ('aktif', models.BooleanField(default=True)),
                ('aciklama', models.CharField(blank=True, max_length=250)),
            ],
            options={
                'ordering': ['ad'],
            },
        ),
        migrations.CreateModel(
            name='IsAltTuru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=160)),
                ('aktif', models.BooleanField(default=True)),
                ('is_turu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alt_turler', to='talepler.isturu')),
            ],
            options={
                'ordering': ['is_turu__ad', 'ad'],
            },
        ),
        migrations.CreateModel(
            name='Talep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talep_no', models.CharField(blank=True, max_length=30, unique=True)),
                ('vatandas_ad', models.CharField(max_length=100)),
                ('vatandas_soyad', models.CharField(max_length=100)),
                ('telefon', models.CharField(max_length=20)),
                ('eposta', models.EmailField(blank=True, max_length=254)),
                ('kapi_no', models.CharField(blank=True, max_length=30)),
                ('adres_aciklama', models.TextField(blank=True)),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('aciklama', models.TextField()),
                ('oncelik', models.CharField(choices=[('dusuk', 'Düşük'), ('normal', 'Normal'), ('yuksek', 'Yüksek'), ('acil', 'Acil')], default='normal', max_length=20)),
                ('durum', models.CharField(choices=[('yeni', 'Yeni'), ('sefe_gonderildi', 'Koordinatöre Gönderildi'), ('sahaya_atandi', 'Sahaya Atandı'), ('kabul_edildi', 'Saha Kabul Etti'), ('yolda', 'Yola Çıkıldı'), ('islemde', 'İşlemde'), ('tamamlandi', 'Tamamlandı'), ('iptal', 'İptal')], default='yeni', max_length=30)),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('guncellenme_tarihi', models.DateTimeField(auto_now=True)),
                ('tamamlanma_tarihi', models.DateTimeField(blank=True, null=True)),
                ('ilce', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='talepler', to='adres.ilce')),
                ('is_alt_turu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='talepler', to='talepler.isaltturu')),
                ('is_turu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='talepler', to='talepler.isturu')),
                ('mahalle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='talepler', to='adres.mahalle')),
                ('olusturan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='olusturdugu_talepler', to=settings.AUTH_USER_MODEL)),
                ('sorumlu_koordinator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='koordinator_talepleri', to='accounts.personelprofili')),
                ('sorumlu_saha', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saha_talepleri', to='accounts.personelprofili')),
                ('yol', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='talepler', to='adres.yol')),
            ],
            options={
                'ordering': ['-olusturulma_tarihi'],
            },
        ),
        migrations.CreateModel(
            name='IslemLogu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('islem', models.CharField(max_length=80)),
                ('aciklama', models.TextField(blank=True)),
                ('varlik_turu', models.CharField(blank=True, max_length=80)),
                ('varlik_id', models.CharField(blank=True, max_length=80)),
                ('eski_deger', models.TextField(blank=True)),
                ('yeni_deger', models.TextField(blank=True)),
                ('ip_adresi', models.GenericIPAddressField(blank=True, null=True)),
                ('tarih', models.DateTimeField(auto_now_add=True)),
                ('kullanici', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('talep', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loglar', to='talepler.talep')),
            ],
            options={
                'ordering': ['-tarih'],
            },
        ),
        migrations.CreateModel(
            name='GeriBildirim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mesaj', models.TextField()),
                ('durum', models.CharField(blank=True, max_length=30)),
                ('tarih', models.DateTimeField(auto_now_add=True)),
                ('sistem_mesaji', models.BooleanField(default=False)),
                ('kullanici', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('talep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geri_bildirimler', to='talepler.talep')),
            ],
            options={
                'ordering': ['-tarih'],
            },
        ),
        migrations.AddConstraint(
            model_name='isaltturu',
            constraint=models.UniqueConstraint(fields=('is_turu', 'ad'), name='uq_is_turu_alt_turu'),
        ),
        migrations.AddIndex(
            model_name='talep',
            index=models.Index(fields=['durum', 'ilce'], name='talepler_ta_durum_430f1d_idx'),
        ),
        migrations.AddIndex(
            model_name='talep',
            index=models.Index(fields=['olusturulma_tarihi'], name='talepler_ta_olustur_936b30_idx'),
        ),
        migrations.AddIndex(
            model_name='islemlogu',
            index=models.Index(fields=['tarih', 'islem'], name='talepler_is_tarih_b4eb17_idx'),
        ),
    ]
