# Generated by Django 6.0.8 on 2026-09-03 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talepler', '0007_v42_dinamik_zorunlu_fotograf'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='abone',
            new_name='talepler_ab_aktif_ca96e1_idx',
            old_name='talepler_ab_aktif_5b163e_idx',
        ),
        migrations.RenameIndex(
            model_name='isemri',
            new_name='talepler_is_durum_87e769_idx',
            old_name='talepler_is_durum_21540a_idx',
        ),
        migrations.RenameIndex(
            model_name='isemri',
            new_name='talepler_is_gondere_79f19d_idx',
            old_name='talepler_is_gonder_7e5dc4_idx',
        ),
        migrations.RenameIndex(
            model_name='mobilbildirim',
            new_name='talepler_mo_kullani_6b283c_idx',
            old_name='talepler_mo_kullani_b24c88_idx',
        ),
        migrations.RenameIndex(
            model_name='vatandasaramakaydi',
            new_name='talepler_va_talep_i_2d2b83_idx',
            old_name='talepler_va_talep_i_2d6f3b_idx',
        ),
        migrations.RenameIndex(
            model_name='vatandasaramakaydi',
            new_name='talepler_va_sonuc_0e81a1_idx',
            old_name='talepler_va_sonuc_i_193aa5_idx',
        ),
    ]
