from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounts", "0001_initial"),
        ("adres", "0001_initial"),
        ("devirambar", "0003_abonelik_devir_akisi"),
    ]

    operations = [
        migrations.CreateModel(
            name="VatandasSicili",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("sicil_no", models.CharField(blank=True, db_index=True, max_length=30, unique=True)),
                ("tc_kimlik_no", models.CharField(db_index=True, max_length=11, unique=True)),
                ("ad", models.CharField(max_length=100)),
                ("soyad", models.CharField(max_length=100)),
                ("dogum_tarihi", models.DateField(blank=True, null=True)),
                ("aktif", models.BooleanField(db_index=True, default=True)),
                ("olusturulma_tarihi", models.DateTimeField(auto_now_add=True)),
                ("guncellenme_tarihi", models.DateTimeField(auto_now=True)),
                ("olusturan", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="olusturdugu_vatandas_sicilleri", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["ad", "soyad", "sicil_no"]},
        ),
        migrations.CreateModel(
            name="Ambar",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("kod", models.SlugField(max_length=80, unique=True)),
                ("ad", models.CharField(max_length=160)),
                ("tur", models.CharField(choices=[("ilce", "İlçe / Yerel Ambar"), ("merkez", "Merkez Ambar"), ("hurda", "Hurda Ambar")], max_length=20)),
                ("aktif", models.BooleanField(db_index=True, default=True)),
                ("aciklama", models.CharField(blank=True, max_length=300)),
                ("ilce", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="ambarlari", to="adres.ilce")),
            ],
            options={"ordering": ["tur", "ad"]},
        ),
        migrations.CreateModel(
            name="HizmetAdresi",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("adres_kodu", models.CharField(db_index=True, max_length=40, unique=True)),
                ("mahalle", models.CharField(max_length=120)),
                ("cadde_sokak", models.CharField(max_length=180)),
                ("kapi_no", models.CharField(max_length=30)),
                ("daire_no", models.CharField(blank=True, max_length=30)),
                ("adres_notu", models.CharField(blank=True, max_length=250)),
                ("aktif", models.BooleanField(db_index=True, default=True)),
                ("olusturulma_tarihi", models.DateTimeField(auto_now_add=True)),
                ("ilce", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="abonelik_hizmet_adresleri", to="adres.ilce")),
            ],
            options={"ordering": ["ilce__ad", "adres_kodu"]},
        ),
        migrations.CreateModel(
            name="VatandasIletisim",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("tur", models.CharField(choices=[("cep_telefonu", "Cep Telefonu"), ("eposta", "E-posta"), ("sabit_telefon", "Sabit Telefon"), ("diger", "Diğer")], max_length=30)),
                ("deger", models.CharField(max_length=180)),
                ("aktif", models.BooleanField(db_index=True, default=True)),
                ("baslangic_tarihi", models.DateTimeField(default=django.utils.timezone.now)),
                ("bitis_tarihi", models.DateTimeField(blank=True, null=True)),
                ("aciklama", models.CharField(blank=True, max_length=250)),
                ("kaydeden", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="kaydettigi_vatandas_iletisimleri", to=settings.AUTH_USER_MODEL)),
                ("sicil", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="iletisim_kayitlari", to="abonelik.vatandassicili")),
            ],
            options={"ordering": ["-aktif", "-baslangic_tarihi"]},
        ),
        migrations.CreateModel(
            name="Sozlesme",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("sozlesme_no", models.CharField(blank=True, db_index=True, max_length=40, unique=True)),
                ("abone_no", models.CharField(db_index=True, max_length=50, unique=True)),
                ("abonelik_turu", models.CharField(choices=[("mesken", "Mesken"), ("isyeri", "İşyeri"), ("kurum", "Kurum / Şirket"), ("insaat", "İnşaat"), ("diger", "Diğer")], default="mesken", max_length=20)),
                ("kaynak", models.CharField(choices=[("ilk_abonelik", "İlk Abonelik"), ("devir", "Devir"), ("e_devlet", "E-Devlet"), ("sanal_sube", "Sanal Şube"), ("ilce_sube", "İlçe Şube"), ("diger", "Diğer")], default="ilce_sube", max_length=20)),
                ("aktif", models.BooleanField(db_index=True, default=True)),
                ("baslangic_tarihi", models.DateField(default=django.utils.timezone.localdate)),
                ("bitis_tarihi", models.DateField(blank=True, null=True)),
                ("aciklama", models.CharField(blank=True, max_length=300)),
                ("olusturulma_tarihi", models.DateTimeField(auto_now_add=True)),
                ("guncellenme_tarihi", models.DateTimeField(auto_now=True)),
                ("adres", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="sozlesmeler", to="abonelik.hizmetadresi")),
                ("devir_basvurusu", models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="abonelik_sozlesmesi", to="devirambar.devirbasvurusu")),
                ("olusturan", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="olusturdugu_sozlesmeler", to=settings.AUTH_USER_MODEL)),
                ("sicil", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="sozlesmeler", to="abonelik.vatandassicili")),
            ],
            options={"ordering": ["-aktif", "-baslangic_tarihi", "abone_no"]},
        ),
        migrations.CreateModel(
            name="SayacEnvanteri",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("sayac_no", models.CharField(db_index=True, max_length=80, unique=True)),
                ("seri_no", models.CharField(db_index=True, max_length=80, unique=True)),
                ("marka_model", models.CharField(blank=True, max_length=140)),
                ("sayac_tipi", models.CharField(choices=[("mekanik", "Mekanik"), ("akilli", "Akıllı"), ("on_odemeli", "Ön Ödemeli"), ("diger", "Diğer")], default="mekanik", max_length=20)),
                ("cap_mm", models.PositiveSmallIntegerField(default=20)),
                ("son_endeks", models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ("durum", models.CharField(choices=[("stokta", "Stokta"), ("aboneye_takili", "Aboneye Takılı"), ("sevk_ediliyor", "Sevk Ediliyor"), ("kontrol_bekliyor", "Kontrol Bekliyor"), ("kullanim_disi", "Kullanım Dışı"), ("hurda", "Hurda Ambarda")], db_index=True, default="stokta", max_length=30)),
                ("aktif", models.BooleanField(db_index=True, default=True)),
                ("hurda_nedeni", models.CharField(blank=True, max_length=250)),
                ("olusturulma_tarihi", models.DateTimeField(auto_now_add=True)),
                ("guncellenme_tarihi", models.DateTimeField(auto_now=True)),
                ("ambar", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="sayaclar", to="abonelik.ambar")),
            ],
            options={"ordering": ["sayac_no"]},
        ),
        migrations.CreateModel(
            name="AboneSayac",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("aktif", models.BooleanField(db_index=True, default=True)),
                ("takilma_tarihi", models.DateField(default=django.utils.timezone.localdate)),
                ("sokulme_tarihi", models.DateField(blank=True, null=True)),
                ("ilk_endeks", models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ("son_endeks", models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ("aciklama", models.CharField(blank=True, max_length=250)),
                ("sayac", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="abone_baglantilari", to="abonelik.sayacenvanteri")),
                ("sozlesme", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="sayac_baglantilari", to="abonelik.sozlesme")),
            ],
            options={"ordering": ["-aktif", "-takilma_tarihi"]},
        ),
        migrations.CreateModel(
            name="AmbarYetkisi",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("aktif", models.BooleanField(default=True)),
                ("atanma_tarihi", models.DateTimeField(auto_now_add=True)),
                ("ambar", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="yetkiler", to="abonelik.ambar")),
                ("ilce", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="ambar_yetkisi", to="adres.ilce")),
                ("personel", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="ambar_yetkileri", to="accounts.personelprofili")),
            ],
            options={"ordering": ["ilce__ad"]},
        ),
        migrations.CreateModel(
            name="AmbarSayacTalebi",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("talep_no", models.CharField(blank=True, db_index=True, max_length=40, unique=True)),
                ("sayac_tipi", models.CharField(choices=[("mekanik", "Mekanik"), ("akilli", "Akıllı"), ("on_odemeli", "Ön Ödemeli"), ("diger", "Diğer")], default="mekanik", max_length=20)),
                ("cap_mm", models.PositiveSmallIntegerField(default=20)),
                ("adet", models.PositiveSmallIntegerField(default=1)),
                ("gerekce", models.CharField(max_length=300)),
                ("durum", models.CharField(choices=[("talep_edildi", "Talep Edildi"), ("hazirlaniyor", "Merkezde Hazırlanıyor"), ("sevk_edildi", "İlçe Ambarına Sevk Edildi"), ("teslim_alindi", "İlçe Ambarı Teslim Aldı"), ("reddedildi", "Reddedildi")], db_index=True, default="talep_edildi", max_length=30)),
                ("talep_tarihi", models.DateTimeField(auto_now_add=True)),
                ("sevk_tarihi", models.DateTimeField(blank=True, null=True)),
                ("teslim_tarihi", models.DateTimeField(blank=True, null=True)),
                ("not_alani", models.CharField(blank=True, max_length=300)),
                ("hedef_ambar", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="hedef_sayac_talepleri", to="abonelik.ambar")),
                ("kaynak_ambar", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="kaynak_sayac_talepleri", to="abonelik.ambar")),
                ("merkez_islem_yapan", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="islem_yaptigi_ambar_sayac_talepleri", to=settings.AUTH_USER_MODEL)),
                ("olusturan", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="olusturdugu_ambar_sayac_talepleri", to=settings.AUTH_USER_MODEL)),
                ("yetki", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="sayac_talepleri", to="abonelik.ambaryetkisi")),
            ],
            options={"ordering": ["-talep_tarihi"]},
        ),
        migrations.CreateModel(
            name="AmbarHareketi",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("islem", models.CharField(choices=[("stok_giris", "Stok Girişi"), ("sayac_talebi", "Sayaç Talebi"), ("sevk", "Ambarlar Arası Sevk"), ("teslim", "Teslim Alma"), ("aboneye_takma", "Aboneye Takma"), ("aboneden_sokme", "Aboneden Sökme"), ("hurdaya_ayirma", "Hurda Ambara Yönlendirme")], max_length=30)),
                ("aciklama", models.CharField(blank=True, max_length=350)),
                ("tarih", models.DateTimeField(auto_now_add=True)),
                ("hedef_ambar", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="giris_hareketleri", to="abonelik.ambar")),
                ("kaynak_ambar", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="cikis_hareketleri", to="abonelik.ambar")),
                ("kullanici", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="ambar_hareketleri", to=settings.AUTH_USER_MODEL)),
                ("sayac", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="ambar_hareketleri", to="abonelik.sayacenvanteri")),
                ("talep", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="hareketler", to="abonelik.ambarsayactalebi")),
            ],
            options={"ordering": ["-tarih"]},
        ),
        migrations.AddConstraint(model_name="abonesayac", constraint=models.UniqueConstraint(fields=("sozlesme", "sayac", "takilma_tarihi"), name="uq_abone_sayac_tarih")),
        migrations.AddIndex(model_name="vatandassicili", index=models.Index(fields=["aktif", "tc_kimlik_no"], name="abonelik_vat_aktif_tc_idx")),
        migrations.AddIndex(model_name="vatandasiletisim", index=models.Index(fields=["sicil", "tur", "aktif"], name="abonelik_iletisim_idx")),
        migrations.AddIndex(model_name="hizmetadresi", index=models.Index(fields=["ilce", "aktif"], name="abonelik_adres_ilce_idx")),
        migrations.AddIndex(model_name="sozlesme", index=models.Index(fields=["sicil", "aktif"], name="abonelik_soz_sicil_idx")),
        migrations.AddIndex(model_name="sozlesme", index=models.Index(fields=["adres", "aktif"], name="abonelik_soz_adres_idx")),
        migrations.AddIndex(model_name="sayacenvanteri", index=models.Index(fields=["durum", "ambar"], name="abonelik_sayac_ambar_idx")),
        migrations.AddIndex(model_name="ambarsayactalebi", index=models.Index(fields=["durum", "talep_tarihi"], name="abonelik_talep_durum_idx")),
        migrations.AddIndex(model_name="ambarhareketi", index=models.Index(fields=["tarih", "islem"], name="abonelik_hareket_idx")),
    ]