# Generated by Django 6.0.8 on 2026-08-19 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ilce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=100, unique=True)),
                ('aktif', models.BooleanField(default=True)),
                ('merkez_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('merkez_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
            ],
            options={
                'ordering': ['ad'],
            },
        ),
        migrations.CreateModel(
            name='Mahalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=150)),
                ('aktif', models.BooleanField(default=True)),
                ('merkez_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('merkez_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('ilce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mahalleler', to='adres.ilce')),
            ],
            options={
                'ordering': ['ilce__ad', 'ad'],
            },
        ),
        migrations.CreateModel(
            name='Yol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=200)),
                ('tur', models.CharField(choices=[('cadde', 'Cadde'), ('sokak', 'Sokak'), ('bulvar', 'Bulvar'), ('meydan', 'Meydan'), ('diger', 'Diğer')], default='sokak', max_length=20)),
                ('aktif', models.BooleanField(default=True)),
                ('merkez_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('merkez_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('mahalle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yollar', to='adres.mahalle')),
            ],
            options={
                'ordering': ['mahalle__ilce__ad', 'mahalle__ad', 'ad'],
            },
        ),
        migrations.AddConstraint(
            model_name='mahalle',
            constraint=models.UniqueConstraint(fields=('ilce', 'ad'), name='uq_ilce_mahalle'),
        ),
        migrations.AddConstraint(
            model_name='yol',
            constraint=models.UniqueConstraint(fields=('mahalle', 'ad'), name='uq_mahalle_yol'),
        ),
    ]
